### ISSUE TITLE
Probably not unicode safe

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-output-sns#7]
This plugin uses String#slice to ensure that messages sizes are accepted by SNS. This check doesn't work for Unicode multibyte chars, and should truncate to the last unicode char < LIMIT.

**Comment by ph** [comment]
you can use `#byteslice` ?

**Comment by andrewvc** [comment]
@ph I think it needs something fancier as #byteslice can split a unicode char in half. I'll tackle this guy once I'm done with all the unit tests I'm currently writing.

**Comment by ph** [comment]
in a previous life I used this `ActiveSupport::Multibyte::Chars` http://api.rubyonrails.org/classes/ActiveSupport/Multibyte/Chars.html#method-i-limit might be worth a check?

**Comment by andrewvc** [comment]
Thanks @ph . It looks like that method determines the final byte with this method: https://github.com/rails/rails/blob/3e36db4406beea32772b1db1e9a16cc1e8aea14c/activesupport/lib/active_support/multibyte/chars.rb#L211 I'll take a look at this in a bit.

**Comment by ph** [comment]
+1, This could be probably an helper class from `logstash-core`?

**Comment by andrewvc** [comment]
@ph I'll create it there then then create a PR for logstash-core.

**Comment by andrewvc** [comment]
Fixed in #10
